import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "../globals.css";
import { Button } from "@/components/ui/button";
import { Header } from "@/components/header";
import { Suspense } from 'react';
import LoadingWidget from '@/components/loading';
import Loading from './loading';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <Suspense fallback={<Loading/>}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header/>
          <div className='min-h-screen h-auto dark:bg-black bg-white  dark:bg-grid-white/[0.06] bg-grid-black/[0.06] relative pt-24'>
            {children}
          </div>
        </ThemeProvider>
    </Suspense>
  );
}
